title: A320neo Checklist
description: >-
  An A320neo checklist for MSFS 2020 for use with SimBrief and Self Loading
  Cargo.
author: Dom Davis
root: /config
exclude:
  - README.md
  - LICENSE
  - Makefile
  - .gitignore
  - checklist.iml
